# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

# This ensures sequential execution within the pipeline
lockBehavior: sequential

jobs:
  - job: BuildAndDeploy
    displayName: 'Build and Deploy ASP.NET Core React App'
    steps:
      # Install dependencies for React app
      - script: |
          cd sdonboarding.client
          npm install
        displayName: 'Install React dependencies'

      # Build the React app
      - script: |
          cd sdonboarding.client
          npm run build
        displayName: 'Build React app'

      # Restore dependencies for .NET Core
      - script: |
          cd sdonboarding.Server
          dotnet restore
        displayName: 'Restore .NET Core dependencies'

      # Build the .NET Core app
      - script: |
          cd sdonboarding.Server
          dotnet build --configuration Release
        displayName: 'Build .NET Core app'

      # Publish the .NET Core app
      - script: |
          cd sdonboarding.Server
          dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/publish
        displayName: 'Publish .NET Core app'
      
      # Copy the React build to the publish directory (from ClientApp to ServerApp/wwwroot)
      - script: |
          cp -r ClientApp/build $(Build.ArtifactStagingDirectory)/publish/wwwroot
        displayName: 'Copy React app build to publish directory'